---
- hosts: 172.31.35.124
  become:
  tasks:
  - include_tasks: myfile.yml
  - name: install webservers
    apt:
     name: apache2
     state: present

  - name: start webserver
    service:
      name: apache2
      state: started






     
