---
- name: deploy java application on ansible node side
  get_url:
    url: https://maha52iaccc.s3.us-east-2.amazonaws.com/mahaLogin.war
    dest: /opt/tomcat/webapps/mahaLogin.war
    force_basic_auth: yes